# Generated by Django 4.1.7 on 2023-03-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AR', 'статья'), ('NE', 'новость')], default='NE', max_length=2),
        ),
    ]
