# Generated by Django 4.1.7 on 2023-04-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_rename_subscription_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rate_comment',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text_comment',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_comment',
            new_name='user',
        ),
    ]
