# Generated by Django 4.2.1 on 2023-06-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_advert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
