# Generated by Django 4.2.1 on 2023-05-30 11:08

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
