# Generated by Django 4.2.1 on 2023-06-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_advert_author_delete_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='text',
            new_name='content',
        ),
    ]
