# Generated by Django 4.2.3 on 2023-07-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkuser',
            name='avatar',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
