# Generated by Django 4.2.3 on 2023-07-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkuser',
            name='avatar',
            field=models.ImageField(default='static/uploads/default_avatar.png', upload_to='static/uploads/'),
        ),
    ]
