openapi: 3.0.2
info:
  title: 'newsapp'
  version: ''

paths:
  /news/:
    get:
      operationId: posts
      description: ''
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://127.0.0.1:8000/news/?offset=400&limit=100
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://127.0.0.1:8000/news/?offset=200&limit=100
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
          description: ''
      tags:
      - posts

  /authors/{id}/:
    get:
      operationId: retrieveAuthor
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this author.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
          description: ''
      tags:
      - authors

components:
  schemas:
    Post:
      type: object
      properties:
        title:
          type: string



#paths:
#  /news/:
#    get:
#      operationId: news
#      description: 'news at News Portal'
#      parameters: []
#      responses:
#        '200':
#          content:
#            application/json:
#              schema:
#                type: array
#                items:
#                  $ref: '#/components/schemas/Post'
#        descriptions: 'abc'
#      tags:
#        - news
#
#schemas:
#  Post:
#    type: object
#    properties:
#      id:
#        type: integer
#        readOnly: true
#      name: string
#      maxLength: 64
#    required:
#      - name