# Generated by Django 4.1.7 on 2023-02-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_staff_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
