from django.views.debug import ExceptionReporter, DEBUG_ENGINE
from django.template import Context

# Шаблон письма (текст) в идеале убрать в отдельный файл
TECHNICAL_500 = """{% firstof exception_type 'Report' %}{% if request %} at {{ request.path_info }}{% endif %}
{% firstof exception_value 'No exception message supplied' %}
{% if request %}
Request Method: {{ request.META.REQUEST_METHOD }}
Request URL: {{ request_insecure_uri }}{% endif %}
Django Version: {{ django_version_info }}
Python Version: {{ sys_version_info }}
Server time: {{server_time|date:"r"}}
{% if template_does_not_exist %}Template loader postmortem
{% if postmortem %}Django tried loading these templates, in this order:
{% for entry in postmortem %}
Using engine {{ entry.backend.name }}:
{% if entry.tried %}{% for attempt in entry.tried %}    * {{ attempt.0.loader_name }}: {{ attempt.0.name }} ({{ attempt.1 }})
{% endfor %}{% else %}    This engine did not provide a list of tried templates.
{% endif %}{% endfor %}
{% else %}No templates were found because your 'TEMPLATES' setting is not configured.
{% endif %}
{% endif %}{% if template_info %}
Template error:
In template {{ template_info.name }}, error at line {{ template_info.line }}
   {{ template_info.message }}
{% for source_line in template_info.source_lines %}{% if source_line.0 == template_info.line %}   {{ source_line.0 }} : {{ template_info.before }} {{ template_info.during }} {{ template_info.after }}{% else %}   {{ source_line.0 }} : {{ source_line.1 }}{% endif %}{% endfor %}{% endif %}

{% if not is_email %}
You’re seeing this error because you have DEBUG = True in your
Django settings file. Change that to False, and Django will
display a standard page generated by the handler for this status code.
{% endif %}"""


# Переопределяем метод получения текста email
class CustomErrorReporter(ExceptionReporter):
    def get_traceback_text(self):
        """Return plain text version of debug 500 HTTP error page."""
        t = DEBUG_ENGINE.from_string(TECHNICAL_500)
        c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
        return t.render(c)
